### ISSUE TITLE
yarn lib  报错

### ISSUE THREAD

**Issue by instanceofs** [ShihaoXiong/xFrameUI#1]
执行：yarn lib 
报错 ：
-  Building for production as library (commonjs,umd,umd-min)... ERROR  TypeError: Cannot set property 'title' of undefined
TypeError: Cannot set property 'title' of undefined

**Comment by instanceofs** [comment]
#vue.config.js 屏蔽 
![image](https://user-images.githubusercontent.com/5299813/129072949-de412c85-af47-4758-8676-6b75f177f9f1.png)
#yarn lib
![image](https://user-images.githubusercontent.com/5299813/129073150-f75e1b18-f94c-4e08-807f-75f4e6383672.png)
# 插件 webpack-chain 报错
https://github.com/neutrinojs/webpack-chain/issues/204
![image](https://user-images.githubusercontent.com/5299813/129073356-93d6c4ee-286c-4284-9858-e70819094b27.png)

**Comment by ShihaoXiong** [comment]
I used the "pages" feature to replace the original method, and it now will no longer throw error when running `yarn lib` or `npm run lib`.
